// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wxrjpnvylteooaoiyrwv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind4cmpwbnZ5bHRlb29hb2l5cnd2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI4NDA1OTEsImV4cCI6MjA1ODQxNjU5MX0.TtmH34U9IZfUmc1pbiRknij9yqRQ39iWyuPjUQyjGNk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);